language: python
python:
  - "3.5"

# install dependencies
install:
  - pip3 install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - unittest tests 

after_success:
  - coveralls
