language: python
python:
  - "3.5"

# install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install -r test_requirements.txt

script:
  - coverage run --source="sjcx_payments" setup.py test

after_success:
  - coveralls

notifications:
  email: false
