language: python
python:
  - "3.4"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

services:
  - mongodb

before_script:
  - mongorestore --port 27017 --db GroupB dump/GroupB

script:
  - coverage run --source="sjcx_payments" setup.py test

after_success:
  - coveralls

notifications:
  email: false
