language: python
python:
  - "3.5"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run --source="sjcx_payments" -m unittest tests

after_success:
  - coveralls

notifications:
  email: false
